### ISSUE TITLE
Buttons cannot be tapped?

### ISSUE THREAD

**Issue by amigax** [GONZALEZD/flutter_wall_layout#1]
How do you tap them and do something?

**Comment by GONZALEZD** [comment]
Hi amigax,

This widget works as a ListView, its a layout, not a set of buttons. Tap handler is not related to WallLayout widget.

Can you be more precise please ? 
Can you provide an example of your problem?

**Comment by amigax** [comment]
Oh I thought they were meant to be buttons, whats the point of it if not?

**Comment by GONZALEZD** [comment]
It's in the name, wall layout... XP
It's meant to **draw** items (of different dimensions) as a wall (like Maya walls).
It's a lack of design if I make items clickable.

Kindly read Readme.md, I think it's a good start for every Flutter packages and plugins ;)
