### ISSUE TITLE
Provide solution for onTap or Gesture on Stones and also provide callback value as int for handling operations 

### ISSUE THREAD

**Issue by ajinkya446** [GONZALEZD/flutter_wall_layout#2]
Provide solution for onTap or Gesture on Stones and also provide callback value as int for handling operations 

    Stone(
            id: data.indexOf(d),
            width: width,
            height: height,
            child: __buildStoneChild(
              background: d["color"] as Color,
              text: "${width}x$height",
              surface: (width * height).toDouble(),
            ),
          )

want to perform the operation on each stone separately for resizing each stone height and width and can not able to get the index for the specific stone

**Comment by GONZALEZD** [comment]
Hi,
you can achieve what you want by wrapping the WallLayout widget into a Widget you created, maybe statefull, that will retain/update the Stones list.

The WallLayout widget only aims to layout its children in a specific manner. It is not intended to do something else.
That's the reason why I reject you suggestion.
